//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.revision = new HashSet<revision>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_ensamble { get; set; }
        public string color { get; set; }
        public string tipo { get; set; }
        public int voltaje { get; set; }
        public string almacen { get; set; }
        public string modelo { get; set; }
        public double precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revision> revision { get; set; }
    }
}
