//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revision
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int empleado_id { get; set; }
        public int producto_id { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_revision { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual persona persona1 { get; set; }
        public virtual producto producto { get; set; }
    }
}
